### ISSUE TITLE
Please restore support for Perl <5.8

### ISSUE THREAD

**Issue by kentfredric** [tokuhirom/Test-Requires#11]
Starting with version 0.007, Perl support regressed from 5.6 as the lowest to being 5.008_001 as the lowest.

0.007's Build.PL arbitrarily enforces 5.008_001 as a minimum, even though the main PM does not.
0.008's Makefile.PL does the same thing.

This may be a design limitation of Minila or something. However, I can't see any [codewise runtime changes](https://github.com/tokuhirom/Test-Requires/commit/5af4fd609a3f2100e470227023e2808ff25a3c9d) in the commit that introduced this change of perl version support.

Thanks in advance. 

/cc @ribasushi

**Comment by tokuhirom** [comment]
I guess most of users don't use perl 5.6.

**Comment by karenetheridge** [comment]
Test::Requires is *very* high up the CPAN River right now -- in fact it is the 2nd-highest non-dual-life module there is:  https://gist.githubusercontent.com/dagolden/f2392a85dc407bb8cae8/raw/e24160dde82f4cc8487aa2bc14f094c544ff6ab7/dag-river-req-only.txt

Since it appears that this distribution does not actually *require* 5.8, it would be greatly helpful if it lowered its minimum requirement to 5.6, to enable its dependencies to also run on 5.6 and allow other distributions to start using it -- some distributions cannot use it because of this prereq.

Please reopen this ticket - thank you!

**Comment by kentfredric** [comment]
See also: https://github.com/tokuhirom/Minilla/issues/167

**Comment by miyagawa** [comment]
Build files generated by Minilla, be it Module::Build or Module::Build::Tiny (now the default) ends up using CPAN::Meta in the configure time, and CPAN::Meta requires 5.8.1.

**Comment by karenetheridge** [comment]
> Build files generated by Minilla, be it Module::Build or Module::Build::Tiny (now the default) ends up using CPAN::Meta in the configure time

Let's fix that then :)

**Comment by miyagawa** [comment]
As stated in https://github.com/tokuhirom/Minilla/issues/167 my personal take is that we don't need to make Minilla complicated to support exotic runtime like 5.6. There are other tools that are capable of doing that already. Minilla can be opinionated and developers who don't agree with that opinion can stay away.

The problem is that the dev here and Minilla dev are the same people, but one can always wear different hats :)

**Comment by miyagawa** [comment]
The bottom line is: Test::Requires has [use 5.006000](https://github.com/tokuhirom/Test-Requires/blob/master/lib/Test/Requires.pm#L6) in its pm, so it must be either:

* allow 5.6 to be able to install this module
* fix this line to match what the distribution requires (which is a requirement forced by Minilla)

There doesn't seem to be an actual use case out there that requires Test::Requires to support 5.6. I bet it is hypothetical - for instance a module that needs to support really old Perl (i.e. Scalar::Util, Carp, DBIC) might want to use Test::Requires and if T::R requires 5.8 they can't.

My take, though, is that is it really the case? The use case where a module needs to support 5.6 is either:

* it is a dual life module that was shipped since 5.6 or older
* it is maintained by some author who wants to support 5.6

In the former case, adding an extra dependency for testing is a no-go anyway - for example, Carp requiring another Test:: module would easily make a circular dependency.

The latter can still be supported, but all Test::Requires does is the same as `eval 'use Module; 1` or plan skip_all => ...` and if one wants to support 5.6, that's not a comparable pain, IMO.

**Comment by karenetheridge** [comment]
My concern is modules using Test::Requires but not realizing that 5.6 installation is now being prevented.  Adding the DEPFAIL status for cpantesters reports will help with this -- we will be able to properly identify which modules would like 5.6 support but are being prevented by their prereqs.

**Comment by kentfredric** [comment]
Just so its clear, with our request is more a "don't block" 5.6, not a "Please support" 5.6

That is:
- we don't expect you to test this yourself
- and we don't expect you to keep an eye on it working on CPAN testers
- and if things break on CPAN testers, we entirely accept you ignoring that.
- people who want 5.6 support for anything that breaks should be the ones finding the solutions
- and all we're asking from you is to apply those solutions when found

**Comment by karenetheridge** [comment]
> and all we're asking from you is to apply those solutions when found

yes, exactly!

**Comment by tokuhirom** [comment]
Finally, I applied Perl 5.6 supporting patch. Thanks!
